<?php

namespace App\ModelsV2;

use App\Helpers\Utility;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Log;
use Webpatser\Uuid\Uuid;

class EchoTechSensorData extends Model
{
    
    protected $table = 'echo_tech';

    protected $fillable = [
        'id',
        'rack_temp',
        'rack_temp_status',
        'at',
        'at_status',
        'rh',
        'rh_status',
        'bp',
        'bp_status',
        'sol_rad',
        'sol_rad_status',
        'rain',
        'rain_status',
        'v_2_5_ref',
        'v_2_5_ref_status',
        'v_0_ref',
        'v_0_ref_status',
        'v_5_ref',
        'v_5_ref_status',
        'ws_raw',
        'ws_raw_status',
        'wd_raw',
        'wd_raw_status',
        'ws_avg',
        'ws_avg_status',
        'wd_avg',
        'wd_avg_status',
        'sigma',
        'sigma_status',
        'pm2_5_conc',
        'pm2_5_conc_status',
        'pm2_5_qtot',
        'pm2_5_qtot_status',
        'pm2_5_rh',
        'pm2_5_rh_status',
        'pm2_5_at',
        'pm2_5_at_status',
        'pm2_5_maint',
        'pm2_5_maint_status',
        'pm2_5_pwr_fail',
        'pm2_5_pwr_fail_status',
        'pm2_5_ref_memb',
        'pm2_5_ref_memb_status',
        'pm2_5_nz_alarm',
        'pm2_5_nz_alarm_status',
        'pm2_5_flow_alarm',
        'pm2_5_flow_alarm_status',
        'pm2_5_press_alarm',
        'pm2_5_press_alarm_status',
        'pm2_5_spn_chk_error',
        'pm2_5_spn_chk_error_status',
        'pm2_5_cnt_alarm',
        'pm2_5_cnt_alarm_status',
        'pm2_5_tape_alarm',
        'pm2_5_tape_alarm_status',
        'pm10_conc',
        'pm10_conc_status',
        'pm10_qtot',
        'pm10_qtot_status',
        'pm10_rh',
        'pm10_rh_status',
        'pm10_at',
        'pm10_at_status',
        'pm10_maint',
        'pm10_maint_status',
        'pm10_pwr_fail',
        'pm10_pwr_fail_status',
        'pm10_ref_memb',
        'pm10_ref_memb_status',
        'pm10_nz_alarm',
        'pm10_nz_alarm_status',
        'pm10_flow_alarm',
        'pm10_flow_alarm_status',
        'pm10_press_alarm',
        'pm10_press_alarm_status',
        'pm10_span_chk',
        'pm10_span_chk_status',
        'pm10_cnt_alarm',
        'pm10_cnt_alarm_status',
        'pm10_tape_alarm',
        'pm10_tape_alarm_status',
        'o3_conc',
        'o3_conc_status',
        'o3_gas_flow',
        'o3_gas_flow_status',
        'o3_gas_press',
        'o3_gas_press_status',
        'co_conc',
        'co_conc_status',
        'co2_conc',
        'co2_conc_status',
        'co_gas_flow',
        'co_gas_flow_status',
        'co_amb_press',
        'co_amb_press_status',
        'co_chassis_temp',
        'co_chassis_temp_status',
        'co_cooler_v',
        'co_cooler_v_status',
        'no_conc',
        'no_conc_status',
        'no2_conc',
        'no2_conc_status',
        'nox_conc',
        'nox_conc_status',
        'nox_gas_flow',
        'nox_gas_flow_status',
        'nox_gas_press',
        'nox_gas_press_status',
        'nox_amb_press',
        'nox_amb_press_status',
        'so2_conc',
        'so2_conc_status',
        'so2_gas_flow',
        'so2_gas_flow_status',
        'so2_gas_press',
        'so2_gas_press_status',
        'voc_meth_conc',
        'voc_meth_conc_status',
        'voc_non_meth_conc',
        'voc_non_meth_conc_status',
        'voc_total_conc',
        'voc_total_conc_status',
        'voc_cal_conc',
        'voc_cal_conc_status',
        'voc_sample_flow',
        'voc_sample_flow_status',
        'voc_fuel_flow',
        'voc_fuel_flow_status',
        'voc_comb_flow',
        'voc_comb_flow_status',
        'voc_det_meth_Curr',
        'voc_det_meth_Curr_status',
        'voc_det_non_meth_Curr',
        'voc_det_non_meth_Curr_status',
        'voc_det_temp',
        'voc_det_temp_status',
        'point',
        'point_status',
        'hto_alarm',
        'hto_alarm_status',
        'shelter_temp',
        'shelter_temp_status',
        'shelter_RH',
        'shelter_RH_status',
        'voc_oxid_temp',
        'voc_oxid_temp_status',
        'identifier',
    ];

    public static function formatEchoTechData($data){
       
        $id = Uuid::generate() . "";
        $dateTime = Utility::formatDateTimeEchoTech($data['created_at']);

        $result = [
        'id' => $id,
        'rack_temp' => !empty($data['LRackTemp']) ? $data['LRackTemp'] : null,
        'rack_temp_status' => !empty($data['LRackTemp status']) ? $data['LRackTemp status'] : null,
        'at' => !empty($data['AT']) ? $data['AT'] : null,
        'at_status' => !empty($data['AT status']) ? $data['AT status'] : null,
        'rh' => !empty($data['RH']) ? $data['RH'] : null,
        'rh_status' => !empty($data['RH status']) ? $data['RH status'] : null,
        'bp' => !empty($data['BP']) ? $data['BP'] : null,
        'bp_status' => !empty($data['BP status']) ? $data['BP status'] : null,
        'sol_rad' => !empty($data['Sol Rad']) ? $data['Sol Rad'] : null,
        'sol_rad_status' => !empty($data['Sol Rad status']) ? $data['Sol Rad status'] : null,
        'rain' => !empty($data['Rain']) ? $data['Rain'] : null,
        'rain_status' => !empty($data['Rain Status']) ? $data['Rain Status'] : null,
        'v_2_5_ref' => !empty($data['2.5 V Ref']) ? $data['2.5 V Ref'] : null,
        'v_2_5_ref_status' => !empty($data['2.5 V Ref status']) ? $data['2.5 V Ref status'] : null,
        'v_0_ref' => !empty($data['0V Ref']) ? $data['0V Ref'] : null,
        'v_0_ref_status' => !empty($data['0V Ref status']) ? $data['0V Ref status'] : null,
        'v_5_ref' => !empty($data['5V Ref']) ? $data['5V Ref'] : null,
        'v_5_ref_status' => !empty($data['5V Ref status']) ? $data['5V Ref status'] : null,
        'ws_raw' => !empty($data['WS Raw']) ? $data['WS Raw'] : null,
        'ws_raw_status' => !empty($data['WS Raw status']) ? $data['WS Raw status'] : null,
        'wd_raw' => !empty($data['WD Raw']) ? $data['WD Raw'] : null,
        'wd_raw_status' => !empty($data['WD Raw_status']) ? $data['WD Raw_status'] : null,
        'ws_avg' => !empty($data['WS Average']) ? $data['WS Average'] : null,
        'ws_avg_status' => !empty($data['WS Average status']) ? $data['WS Average status'] : null,
        'wd_avg' => !empty($data['WD Average']) ? $data['WD Average'] : null,
        'wd_avg_status' => !empty($data['WD Average status']) ? $data['WD Average status'] : null,
        'sigma' => !empty($data['Sigma']) ? $data['Sigma'] : null,
        'sigma_status' => !empty($data['Sigma status']) ? $data['Sigma status'] : null,
        'pm2_5_conc' => !empty($data['PM2.5 Conc']) ? $data['PM2.5 Conc'] : null,
        'pm2_5_conc_status' => !empty($data['PM2.5 Conc status']) ? $data['PM2.5 Conc status'] : null,
        'pm2_5_qtot' => !empty($data['PM2.5 Qtot']) ? $data['PM2.5 Qtot'] : null,
        'pm2_5_qtot_status' => !empty($data['PM2.5 Qtot status']) ? $data['PM2.5 Qtot status'] : null,
        'pm2_5_rh' => !empty($data['PM2.5 RH']) ? $data['PM2.5 RH'] : null,
        'pm2_5_rh_status' => !empty($data['PM2.5 RH status']) ? $data['PM2.5 RH status'] : null,
        'pm2_5_at' => !empty($data['PM2.5 AT']) ? $data['PM2.5 AT'] : null,
        'pm2_5_at_status' => !empty($data['PM2.5 AT status']) ? $data['PM2.5 AT status'] : null,
        'pm2_5_maint' => !empty($data['PM2.5 Maint']) ? $data['PM2.5 Maint'] : null,
        'pm2_5_maint_status' => !empty($data['PM2.5 Maint status']) ? $data['PM2.5 Maint status'] : null,
        'pm2_5_pwr_fail' => !empty($data['PM2.5 Pwr Fail']) ? $data['PM2.5 Pwr Fail'] : null,
        'pm2_5_pwr_fail_status' => !empty($data['PM2.5 Pwr Fail status']) ? $data['PM2.5 Pwr Fail status'] : null,
        'pm2_5_ref_memb' => !empty($data['PM2.5 Ref Memb']) ? $data['PM2.5 Ref Memb'] : null,
        'pm2_5_ref_memb_status' => !empty($data['PM2.5 Ref Memb status']) ? $data['PM2.5 Ref Memb status'] : null,
        'pm2_5_nz_alarm' => !empty($data['PM2.5 Nz Alarm']) ? $data['PM2.5 Nz Alarm'] : null,
        'pm2_5_nz_alarm_status' => !empty($data['PM2.5 Nz Alarm status']) ? $data['PM2.5 Nz Alarm status'] : null,
        'pm2_5_flow_alarm' => !empty($data['PM2.5 Flow Alarm']) ? $data['PM2.5 Flow Alarm'] : null,
        'pm2_5_flow_alarm_status' => !empty($data['PM2.5 Flow Alarm status']) ? $data['PM2.5 Flow Alarm status'] : null,
        'pm2_5_press_alarm' => !empty($data['PM2.5 Press Alarm']) ? $data['PM2.5 Press Alarm'] : null,
        'pm2_5_press_alarm_status' => !empty($data['PM2.5 Press Alarm status']) ? $data['PM2.5 Press Alarm status'] : null,
        'pm2_5_spn_chk_error' => !empty($data['PM2.5 Spn Chk Error']) ? $data['PM2.5 Spn Chk Error'] : null,
        'pm2_5_spn_chk_error_status' => !empty($data['PM2.5 Spn Chk Error status']) ? $data['PM2.5 Spn Chk Error status'] : null,
        'pm2_5_cnt_alarm' => !empty($data['PM2.5 Cnt Alarm']) ? $data['PM2.5 Cnt Alarm'] : null,
        'pm2_5_cnt_alarm_status' => !empty($data['PM2.5 Cnt Alarm status']) ? $data['PM2.5 Cnt Alarm status'] : null,
        'pm2_5_tape_alarm' => !empty($data['PM2.5 Tape Alarm']) ? $data['PM2.5 Tape Alarm'] : null,
        'pm2_5_tape_alarm_status' => !empty($data['PM2.5 Tape Alarm status']) ? $data['PM2.5 Tape Alarm status'] : null,
        'pm10_conc' => !empty($data['PM10 Conc']) ? $data['PM10 Conc'] : null,
        'pm10_conc_status' => !empty($data['PM10 Conc status']) ? $data['PM10 Conc status'] : null,
        'pm10_qtot' => !empty($data['PM10 Qtot']) ? $data['PM10 Qtot'] : null,
        'pm10_qtot_status' => !empty($data['PM10 Qtot status']) ? $data['PM10 Qtot status'] : null,
        'pm10_rh' => !empty($data['PM10 RH']) ? $data['PM10 RH'] : null,
        'pm10_rh_status' => !empty($data['PM10 RH status']) ? $data['PM10 RH status'] : null,
        'pm10_at' => !empty($data['PM10 AT']) ? $data['PM10 AT'] : null,
        'pm10_at_status' => !empty($data['PM10 AT status']) ? $data['PM10 AT status'] : null,
        'pm10_maint' => !empty($data['PM10 Maint']) ? $data['PM10 Maint'] : null,
        'pm10_maint_status' => !empty($data['PM10 Maint status']) ? $data['PM10 Maint status'] : null,
        'pm10_pwr_fail' => !empty($data['PM10 Pwr Fail']) ? $data['PM10 Pwr Fail'] : null,
        'pm10_pwr_fail_status' => !empty($data['PM10 Pwr Fail status']) ? $data['PM10 Pwr Fail status'] : null,
        'pm10_ref_memb' => !empty($data['PM10 Ref Memb']) ? $data['PM10 Ref Memb'] : null,
        'pm10_ref_memb_status' => !empty($data['PM10 Ref Memb status']) ? $data['PM10 Ref Memb status'] : null,
        'pm10_nz_alarm' => !empty($data['PM10 Nz Alarm']) ? $data['PM10 Nz Alarm'] : null,
        'pm10_nz_alarm_status' => !empty($data['PM10 Nz Alarm status']) ? $data['PM10 Nz Alarm status'] : null,
        'pm10_flow_alarm' => !empty($data['PM10 Flow Alarm']) ? $data['PM10 Flow Alarm'] : null,
        'pm10_flow_alarm_status' => !empty($data['PM10 Flow Alarm status']) ? $data['PM10 Flow Alarm status'] : null,
        'pm10_press_alarm' => !empty($data['PM10 Press Alarm']) ? $data['PM10 Press Alarm'] : null,
        'pm10_press_alarm_status' => !empty($data['PM10 Press Alarm status']) ? $data['PM10 Press Alarm status'] : null,
        'pm10_span_chk' => !empty($data['PM10 Span Chk']) ? $data['PM10 Span Chk'] : null,
        'pm10_span_chk_status' => !empty($data['PM10 Span Chk status']) ? $data['PM10 Span Chk status'] : null,
        'pm10_cnt_alarm' => !empty($data['PM10 Cnt Alarm']) ? $data['PM10 Cnt Alarm'] : null,
        'pm10_cnt_alarm_status' => !empty($data['PM10 Cnt Alarm status']) ? $data['PM10 Cnt Alarm status'] : null,
        'pm10_tape_alarm' => !empty($data['PM10 Tape Alarm']) ? $data['PM10 Tape Alarm'] : null,
        'pm10_tape_alarm_status' => !empty($data['PM10 Tape Alarm status']) ? $data['PM10 Tape Alarm status'] : null,
        'o3_conc' => !empty($data['O3 Conc']) ? $data['O3 Conc'] : null,
        'o3_conc_status' => !empty($data['O3 Conc status']) ? $data['O3 Conc status'] : null,
        'o3_gas_flow' => !empty($data['O3 Gas Flow']) ? $data['O3 Gas Flow'] : null,
        'o3_gas_flow_status' => !empty($data['O3 Gas Flow status']) ? $data['O3 Gas Flow status'] : null,
        'o3_gas_press' => !empty($data['O3 Gas Press']) ? $data['O3 Gas Press'] : null,
        'o3_gas_press_status' => !empty($data['O3 Gas Press status']) ? $data['O3 Gas Press status'] : null,
        'co_conc' => !empty($data['CO Conc']) ? $data['CO Conc'] : null,
        'co_conc_status' => !empty($data['CO Conc status']) ? $data['CO Conc status'] : null,
        'co2_conc' => !empty($data['CO2 Conc']) ? $data['CO2 Conc'] : null,
        'co2_conc_status' => !empty($data['CO2 Conc status']) ? $data['CO2 Conc status'] : null,
        'co_gas_flow' => !empty($data['CO Gas Flow']) ? $data['CO Gas Flow'] : null,
        'co_gas_flow_status' => !empty($data['CO Gas Flow status']) ? $data['CO Gas Flow status'] : null,
        'co_amb_press' => !empty($data['CO Amb Press']) ? $data['CO Amb Press'] : null,
        'co_amb_press_status' => !empty($data['CO Amb Press status']) ? $data['CO Amb Press status'] : null,
        'co_chassis_temp' => !empty($data['CO Chassis Temp']) ? $data['CO Chassis Temp'] : null,
        'co_chassis_temp_status' => !empty($data['CO Chassis Temp status']) ? $data['CO Chassis Temp status'] : null,
        'co_cooler_v' => !empty($data['CO Cooler V']) ? $data['CO Cooler V'] : null,
        'co_cooler_v_status' => !empty($data['CO Cooler V status']) ? $data['CO Cooler V status'] : null,
        'no_conc' => !empty($data['NO Conc']) ? $data['NO Conc'] : null,
        'no_conc_status' => !empty($data['NO Conc status']) ? $data['NO Conc status'] : null,
        'no2_conc' => !empty($data['NO2 Conc']) ? $data['NO2 Conc'] : null,
        'no2_conc_status' => !empty($data['NO2 Conc status']) ? $data['NO2 Conc status'] : null,
        'nox_conc' => !empty($data['NOX Conc']) ? $data['NOX Conc'] : null,
        'nox_conc_status' => !empty($data['NOX Conc status']) ? $data['NOX Conc status'] : null,
        'nox_gas_flow' => !empty($data['NOX Gas Flow']) ? $data['NOX Gas Flow'] : null,
        'nox_gas_flow_status' => !empty($data['NOX Gas Flow status']) ? $data['NOX Gas Flow status'] : null,
        'nox_gas_press' => !empty($data['NOX Gas Press']) ? $data['NOX Gas Press'] : null,
        'nox_gas_press_status' => !empty($data['NOX Gas Press status']) ? $data['NOX Gas Press status'] : null,
        'nox_amb_press' => !empty($data['NOX Amb Press']) ? $data['NOX Amb Press'] : null,
        'nox_amb_press_status' => !empty($data['NOX Amb Press status']) ? $data['NOX Amb Press status'] : null,
        'so2_conc' => !empty($data['SO2 Conc']) ? $data['SO2 Conc'] : null,
        'so2_conc_status' => !empty($data['SO2 Conc status']) ? $data['SO2 Conc status'] : null,
        'so2_gas_flow' => !empty($data['SO2 Gas Flow']) ? $data['SO2 Gas Flow'] : null,
        'so2_gas_flow_status' => !empty($data['SO2 Gas Flow status']) ? $data['SO2 Gas Flow status'] : null,
        'so2_gas_press' => !empty($data['SO2 Gas Press']) ? $data['SO2 Gas Press'] : null,
        'so2_gas_press_status' => !empty($data['SO2 Gas Press']) ? $data['SO2 Gas Press '] : null,
        'voc_meth_conc' => !empty($data['VOC Meth Conc']) ? $data['VOC Meth Conc'] : null,
        'voc_meth_conc_status' => !empty($data['VOC Meth Conc status']) ? $data['VOC Meth Conc status'] : null,
        'voc_non_meth_conc' => !empty($data['VOC Non Meth Conc']) ? $data['VOC Non Meth Conc'] : null,
        'voc_non_meth_conc_status' => !empty($data['VOC Non Meth Conc status']) ? $data['VOC Non Meth Conc status'] : null,
        'voc_total_conc' => !empty($data['VOC Total Conc']) ? $data['VOC Total Conc'] : null,
        'voc_total_conc_status' => !empty($data['VOC Total Conc status']) ? $data['VOC Total Conc status'] : null,
        'voc_cal_conc' => !empty($data['VOC Cal Conc']) ? $data['VOC Cal Conc'] : null,
        'voc_cal_conc_status' => !empty($data['VOC Cal Conc status']) ? $data['VOC Cal Conc status'] : null,
        'voc_sample_flow' => !empty($data['VOC  Sample Flow']) ? $data['VOC  Sample Flow'] : null,
        'voc_sample_flow_status' => !empty($data['VOC  Sample Flow status']) ? $data['VOC  Sample Flow status'] : null,
        'voc_fuel_flow' => !empty($data['VOC Fuel Flow']) ? $data['VOC Fuel Flow'] : null,
        'voc_fuel_flow_status' => !empty($data['VOC Fuel Flow status']) ? $data['VOC Fuel Flow status'] : null,
        'voc_comb_flow' => !empty($data['VOC Comb Flow']) ? $data['VOC Comb Flow'] : null,
        'voc_comb_flow_status' => !empty($data['VOC Comb Flow status']) ? $data['VOC Comb Flow status'] : null,
        'voc_det_meth_curr' => !empty($data['VOC Det Meth Curr']) ? $data['VOC Det Meth Curr'] : null,
        'voc_det_meth_curr_status' => !empty($data['VOC Det Meth Curr status']) ? $data['VOC Det Meth Curr status'] : null,
        'voc_det_non_meth_cur' => !empty($data['VOC Det Non Meth Cur']) ? $data['VOC Det Non Meth Cur'] : null,
        'voc_det_non_meth_cur_status' => !empty($data['VOC Det Non Meth Cur status']) ? $data['VOC Det Non Meth Cur status'] : null,
        'voc_det_temp' => !empty($data['VOC DetTemp']) ? $data['VOC DetTemp'] : null,
        'voc_det_temp_status' => !empty($data['VOC DetTemp status']) ? $data['VOC DetTemp status'] : null,
        'point' => !empty($data['Point']) ? $data['Point'] : null,
        'point_status' => !empty($data['Point status']) ? $data['Point status'] : null,
        'hto_alarm' => !empty($data['HTO Alarm']) ? $data['HTO Alarm'] : null,
        'hto_alarm_status' => !empty($data['HTP Alarm status']) ? $data['HTP Alarm status'] : null,
        'shelter_temp' => !empty($data['Shelter Temp']) ? $data['Shelter Temp'] : null,
        'shelter_temp_status' => !empty($data['Shelter Temp status']) ? $data['Shelter Temp status'] : null,
        'shelter_RH' => !empty($data['Shelter RH']) ? $data['Shelter RH'] : null,
        'shelter_RH_status' => !empty($data['Shelter RH status']) ? $data['Shelter RH status'] : null,
        'voc_oxid_temp' => !empty($data['VOC Oxid Temp']) ? $data['VOC Oxid Temp'] : null,
        'voc_oxid_temp_status' => !empty($data['VOC Oxid Temp status']) ? $data['VOC Oxid Temp status'] : null,
        'identifier' => $data['key'] ?? null,
        'created_at' => $dateTime,
        'updated_at' =>  $dateTime
        ];
         return $result;
    }


}