<script setup>
import AdminLayout from "@/Layouts/AdminLayout.vue";
</script>


<template>
  <AdminLayout>
    <div class="p-4">
      <h1 class="text-2xl font-bold mb-8">Notification Settings</h1>

      <div class="flex items-center justify-between bg-white mt-7">
        <div class="flex items-center">
          <div class="relative">
            <input
              type="text"
              placeholder="Search"
              class="text-green-700 border border-gray-300 placeholder-gray-300 rounded-full pl-10 pr-4 py-2 w-60 focus:outline-none focus:ring-2 focus:ring-green-500"
            />
            <svg
              class="absolute left-3 top-1/2 transform -translate-y-1/2 text-green-700 w-5 h-5"
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M21 21l-4.35-4.35m3.23-4.88a6.375 6.375 0 11-12.75 0 6.375 6.375 0 0112.75 0z"
              />
            </svg>
          </div>
        </div>
        <div class="flex items-center">
          <button class="px-4 ml-4 py-2 bg-green1 text-white rounded-full">
            + Send Notification
          </button>
          <button class="px-4 ml-4 py-2 bg-green1 text-white rounded-full">
            + Notifications Setup
          </button>
        </div>
      </div>

      <div class="container mx-auto my-4">
        <table class="min-w-full bg-white">
          <thead>
            <tr
              class="w-full text-left text-xs font-medium text-gray-400 uppercase tracking-wider"
            >
              <th class="py-3 px-6 text-center">Date & Time</th>
              <th class="py-3 px-6 flex items-center">
                <img
                  src="/images/checkboxicon.svg"
                  alt="Icon"
                  class="mr-2 w-4 h-4"
                />Notification
              </th>
              <th class="py-3 px-6">Description</th>
              <th class="py-3 px-6">Recipients</th>
              <th class="py-3 px-6">Generated by</th>
              <th class="py-3 px-6"></th>
              <!-- Empty header for the three dots column -->
            </tr>
          </thead>
          <tbody>
            <tr class="border-b border-t border-gray-200">
              <td class="py-3 px-4 text-center">
                <div class="text-black">25 Oct 2024</div>
                <div class="text-gray-400">08:56 AM</div>
              </td>
              <td class="py-3 px-6">Daily Summary</td>
              <td class="py-3 px-6">
                Provides a summary of the daily AGI data
              </td>
              <td class="py-3 px-6">admin@123</td>
              <td class="py-3 px-6 text-[#878D96]">Admin1</td>

              <td class="text-right text-gray-500 font-bold cursor-pointer">
                <div class="relative inline-block text-left">
                  <div>
                    <button
                      @click="toggleDropdown"
                      type="button"
                      class="py-3 px-6"
                      id="options-menu"
                      aria-haspopup="true"
                      aria-expanded="true"
                    >
                      &#8942;
                    </button>
                  </div>

                  <div
                    v-if="isOpen"
                    class="font-medium origin-top-right absolute right-0 mt-2 w-56 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 z-10"
                  >
                    <div
                      class="py-1"
                      role="menu"
                      aria-orientation="vertical"
                      aria-labelledby="options-menu"
                    >
                      <a
                        href="#"
                        class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 hover:text-gray-900"
                        role="menuitem"
                        @click="showEditUserModal = true"
                        >Edit User</a
                      >
                      <a
                        href="#"
                        class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 hover:text-gray-900"
                        role="menuitem"
                        >Next Option</a
                      >
                    </div>
                  </div>
                </div>
              </td>
            </tr>

            <tr class="border-b border-t border-gray-200">
              <td class="py-3 px-4 text-center">
                <div class="text-black">25 Oct 2024</div>
                <div class="text-gray-400">08:56 AM</div>
              </td>
              <td class="py-3 px-6">Daily Summary</td>
              <td class="py-3 px-6">
                Provides a summary of the daily AGI data
              </td>
              <td class="py-3 px-6">admin@123</td>
              <td class="py-3 px-6 text-[#878D96]">Admin1</td>

              <td class="text-right text-gray-500 font-bold cursor-pointer">
                <div class="relative inline-block text-left">
                  <div>
                    <button
                      @click="toggleDropdown"
                      type="button"
                      class="py-3 px-6"
                      id="options-menu"
                      aria-haspopup="true"
                      aria-expanded="true"
                    >
                      &#8942;
                    </button>
                  </div>

                  <div
                    v-if="isOpen"
                    class="font-medium origin-top-right absolute right-0 mt-2 w-56 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 z-10"
                  >
                    <div
                      class="py-1"
                      role="menu"
                      aria-orientation="vertical"
                      aria-labelledby="options-menu"
                    >
                      <a
                        href="#"
                        class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 hover:text-gray-900"
                        role="menuitem"
                        @click="showEditUserModal = true"
                        >Edit User</a
                      >
                      <a
                        href="#"
                        class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 hover:text-gray-900"
                        role="menuitem"
                        >Next Option</a
                      >
                    </div>
                  </div>
                </div>
              </td>
            </tr>

            <tr class="border-b border-t border-gray-200">
              <td class="py-3 px-4 text-center">
                <div class="text-black">25 Oct 2024</div>
                <div class="text-gray-400">08:56 AM</div>
              </td>
              <td class="py-3 px-6">Daily Summary</td>
              <td class="py-3 px-6">
                Provides a summary of the daily AGI data
              </td>
              <td class="py-3 px-6">admin@123</td>
              <td class="py-3 px-6 text-[#878D96]">Admin1</td>

              <td class="text-right text-gray-500 font-bold cursor-pointer">
                <div class="relative inline-block text-left">
                  <div>
                    <button
                      @click="toggleDropdown"
                      type="button"
                      class="py-3 px-6"
                      id="options-menu"
                      aria-haspopup="true"
                      aria-expanded="true"
                    >
                      &#8942;
                    </button>
                  </div>

                  <div
                    v-if="isOpen"
                    class="font-medium origin-top-right absolute right-0 mt-2 w-56 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 z-10"
                  >
                    <div
                      class="py-1"
                      role="menu"
                      aria-orientation="vertical"
                      aria-labelledby="options-menu"
                    >
                      <a
                        href="#"
                        class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 hover:text-gray-900"
                        role="menuitem"
                        @click="showEditUserModal = true"
                        >Edit User</a
                      >
                      <a
                        href="#"
                        class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 hover:text-gray-900"
                        role="menuitem"
                        >Next Option</a
                      >
                    </div>
                  </div>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <div class="flex items-center justify-between w-full">
        <button class="px-4 py-1 rounded-lg border border-gray-300">
          Previous
        </button>

        <span class="text-lg text-sm"> <span class="text-sm font-medium"> <span class="text-green1">Page 1</span> of 10 </span> </span>

        <button class="px-3 py-1 rounded-lg border border-gray-300">
          Next
        </button>
      </div>
    </div>
  </AdminLayout>
</template>