<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('echo_tech', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->float('rack_temp')->nullable();
            $table->float('rack_temp_status')->nullable();
            $table->float('at')->nullable();
            $table->float('at_status')->nullable();
            $table->float('rh')->nullable();
            $table->float('rh_status')->nullable();
            $table->float('bp')->nullable();
            $table->float('bp_status')->nullable();
            $table->float('sol_rad')->nullable();
            $table->float('sol_rad_status')->nullable();
            $table->float('rain')->nullable();
            $table->float('rain_status')->nullable();
            $table->float('v_2_5_ref')->nullable();
            $table->float('v_2_5_ref_status')->nullable();
            $table->float('v_0_ref')->nullable();
            $table->float('v_0_ref_status')->nullable();
            $table->float('v_5_ref')->nullable();
            $table->float('v_5_ref_status')->nullable();
            $table->float('ws_raw')->nullable();
            $table->float('ws_raw_status')->nullable();
            $table->float('wd_raw')->nullable();
            $table->float('wd_raw_status')->nullable();
            $table->float('ws_avg')->nullable();
            $table->float('ws_avg_status')->nullable();
            $table->float('wd_avg')->nullable();
            $table->float('wd_avg_status')->nullable();
            $table->float('sigma')->nullable();
            $table->float('sigma_status')->nullable();
            $table->float('pm2_5_conc')->nullable();
            $table->float('pm2_5_conc_status')->nullable();
            $table->float('pm2_5_qtot')->nullable();
            $table->float('pm2_5_qtot_status')->nullable();
            $table->float('pm2_5_rh')->nullable();
            $table->float('pm2_5_rh_status')->nullable();
            $table->float('pm2_5_at')->nullable();
            $table->float('pm2_5_at_status')->nullable();
            $table->float('pm2_5_maint')->nullable();
            $table->float('pm2_5_maint_status')->nullable();
            $table->float('pm2_5_pwr_fail')->nullable();
            $table->float('pm2_5_pwr_fail_status')->nullable();
            $table->float('pm2_5_ref_memb')->nullable();
            $table->float('pm2_5_ref_memb_status')->nullable();
            $table->float('pm2_5_nz_alarm')->nullable();
            $table->float('pm2_5_nz_alarm_status')->nullable();
            $table->float('pm2_5_flow_alarm')->nullable();
            $table->float('pm2_5_flow_alarm_status')->nullable();
            $table->float('pm2_5_press_alarm')->nullable();
            $table->float('pm2_5_press_alarm_status')->nullable();
            $table->float('pm2_5_spn_chk_error')->nullable();
            $table->float('pm2_5_spn_chk_error_status')->nullable();
            $table->float('pm2_5_cnt_alarm')->nullable();
            $table->float('pm2_5_cnt_alarm_status')->nullable();
            $table->float('pm2_5_tape_alarm')->nullable();
            $table->float('pm2_5_tape_alarm_status')->nullable();
            $table->float('pm10_conc')->nullable();
            $table->float('pm10_conc_status')->nullable();
            $table->float('pm10_qtot')->nullable();
            $table->float('pm10_qtot_status')->nullable();
            $table->float('pm10_rh')->nullable();
            $table->float('pm10_rh_status')->nullable();
            $table->float('pm10_at')->nullable();
            $table->float('pm10_at_status')->nullable();
            $table->float('pm10_maint')->nullable();
            $table->float('pm10_maint_status')->nullable();
            $table->float('pm10_pwr_fail')->nullable();
            $table->float('pm10_pwr_fail_status')->nullable();
            $table->float('pm10_ref_memb')->nullable();
            $table->float('pm10_ref_memb_status')->nullable();
            $table->float('pm10_nz_alarm')->nullable();
            $table->float('pm10_nz_alarm_status')->nullable();
            $table->float('pm10_flow_alarm')->nullable();
            $table->float('pm10_flow_alarm_status')->nullable();
            $table->float('pm10_press_alarm')->nullable();
            $table->float('pm10_press_alarm_status')->nullable();
            $table->float('pm10_span_chk')->nullable();
            $table->float('pm10_span_chk_status')->nullable();
            $table->float('pm10_cnt_alarm')->nullable();
            $table->float('pm10_cnt_alarm_status')->nullable();
            $table->float('pm10_tape_alarm')->nullable();
            $table->float('pm10_tape_alarm_status')->nullable();
            $table->float('o3_conc')->nullable();
            $table->float('o3_conc_status')->nullable();
            $table->float('o3_gas_flow')->nullable();
            $table->float('o3_gas_flow_status')->nullable();
            $table->float('o3_gas_press')->nullable();
            $table->float('o3_gas_press_status')->nullable();
            $table->float('co_conc')->nullable();
            $table->float('co_conc_status')->nullable();
            $table->float('co2_conc')->nullable();
            $table->float('co2_conc_status')->nullable();
            $table->float('co_gas_flow')->nullable();
            $table->float('co_gas_flow_status')->nullable();
            $table->float('co_amb_press')->nullable();
            $table->float('co_amb_press_status')->nullable();
            $table->float('co_chassis_temp')->nullable();
            $table->float('co_chassis_temp_status')->nullable();
            $table->float('co_cooler_v')->nullable();
            $table->float('co_cooler_v_status')->nullable();
            $table->float('no_conc')->nullable();
            $table->float('no_conc_status')->nullable();
            $table->float('no2_conc')->nullable();
            $table->float('no2_conc_status')->nullable();
            $table->float('nox_conc')->nullable();
            $table->float('nox_conc_status')->nullable();
            $table->float('nox_gas_flow')->nullable();
            $table->float('nox_gas_flow_status')->nullable();
            $table->float('nox_gas_press')->nullable();
            $table->float('nox_gas_press_status')->nullable();
            $table->float('nox_amb_press')->nullable();
            $table->float('nox_amb_press_status')->nullable();
            $table->float('so2_conc')->nullable();
            $table->float('so2_conc_status')->nullable();
            $table->float('so2_gas_flow')->nullable();
            $table->float('so2_gas_flow_status')->nullable();
            $table->float('so2_gas_press')->nullable();
            $table->float('so2_gas_press_status')->nullable();
            $table->float('voc_meth_conc')->nullable();
            $table->float('voc_meth_conc_status')->nullable();
            $table->float('voc_non_meth_conc')->nullable();
            $table->float('voc_non_meth_conc_status')->nullable();
            $table->float('voc_total_conc')->nullable();
            $table->float('voc_total_conc_status')->nullable();
            $table->float('voc_cal_conc')->nullable();
            $table->float('voc_cal_conc_status')->nullable();
            $table->float('voc_sample_flow')->nullable();
            $table->float('voc_sample_flow_status')->nullable();
            $table->float('voc_fuel_flow')->nullable();
            $table->float('voc_fuel_flow_status')->nullable();
            $table->float('voc_comb_flow')->nullable();
            $table->float('voc_comb_flow_status')->nullable();
            $table->float('voc_det_meth_curr')->nullable();
            $table->float('voc_det_meth_curr_status')->nullable();
            $table->float('voc_det_non_meth_cur')->nullable();
            $table->float('voc_det_non_meth_cur_status')->nullable();
            $table->float('voc_det_temp')->nullable();
            $table->float('voc_det_temp_status')->nullable();
            $table->float('point')->nullable();
            $table->float('point_status')->nullable();
            $table->float('hto_alarm')->nullable();
            $table->float('hto_alarm_status')->nullable();
            $table->float('shelter_temp')->nullable();
            $table->float('shelter_temp_status')->nullable();
            $table->float('shelter_RH')->nullable();
            $table->float('shelter_RH_status')->nullable();
            $table->float('voc_oxid_temp')->nullable();
            $table->float('voc_oxid_temp_status')->nullable();
            $table->string('identifier')->nullable();
            $table->unique('identifier');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('echo_tech');
    }
};
